---
title: Calculate the speed of the ISS using photos
hero_image: images/banner.png
description: Calculate the speed of the ISS using image data
version: 4
listed: true
copyedit: true
last_tested: '2023-10-19'
steps:
- title: Introduction
- title: Use EXIF data to find a time difference
  completion:
  - engaged
- title: Finding the time difference for two photos
- title: Find matching features
- title: Display matching features
- title: Find matching coordinates
- title: Calculate feature distance
- title: Calculate average speed
- title: Improving your program
  completion:
  - internal
- title: What next?
  completion:
  - external
