title: Calculate the speed of the ISS
hero_image: images/banner.png
description: astropi-iss-speed description
version: 4
listed: false
copyedit: false
last_tested: "2022-04-26"
steps:
  - title: Introduction
  - title: Use EXIF data to find a time difference
  - title: Find matching features
  - title: Display matching features
  - title: Find matching coordinates
  - title: Calculate distance and speed
  - title: Upgrade your project
  - title: Enter the third mission